version: '3'
services:
  lucy_database:
    image: "postgres" # use latest official postgres version
    ports:
      - "5432:5432"
    container_name: "lucy_kraken_db"
    # env_file:
    #   - database.env # configure postgres
    volumes:
      - lucy-kraken-db:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./data/:/sql

volumes:
  lucy-kraken-db: # named volumes can be managed easier using docker-compose