name: Deploy to DO
run-name: ${{ github.actor }} is deploying to DO
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          git pull origin master
          pip install -r requirements.txt
          git status